groups:
  - name: antgasp-slo
    rules:
      - alert: HighErrorRateBFF
        expr: |
          sum(rate(http_server_requests_seconds_count{app="bff",status=~"5.."}[5m]))
          /
          sum(rate(http_server_requests_seconds_count{app="bff"}[5m])) > 0.05
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "BFF: taux d'erreur > 5% sur 10m"
      - alert: HighLatencyP95Products
        expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app="products"}[5m])) by (le)) > 0.5
        for: 10m
        labels: { severity: warning }
        annotations:
          summary: "Products: p95 > 500ms"
