server: { port: 8082 }
spring:
  datasource:
    url: jdbc:h2:mem:users;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate: { ddl-auto: update }
    open-in-view: false
