server: { port: 8083 }
spring:
  datasource: { url: jdbc:h2:mem:reservations;DB_CLOSE_DELAY=-1, driverClassName: org.h2.Driver, username: sa, password: "" }
  jpa: { hibernate: { ddl-auto: update }, open-in-view: false }
