name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable

      - name: Web install
        working-directory: apps/web
        run: |
          pnpm install
          pnpm build

      - name: BFF install
        working-directory: apps-bff/bff
        run: |
          pnpm install
          pnpm build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build products
        working-directory: services/products
        run: mvn -q -DskipTests package
