name: security
on: { push: { branches: [ main ] } }
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with: { scan-type: fs, ignore-unfixed: true, format: table, severity: CRITICAL,HIGH }
